#!/bin/bash
#############################################################
###
### How Tomcat Works - Chapter 15 
### Use this Script to run each exercise in Chapter 15
### Uncomment the specificate line to activate the command
###
#############################################################

# common dir
ROOT="/Users/Wei/github/HowTomcatWorks"
WEB_APPS="${ROOT}/webapps/app15/WEB-INF/classes/"
MAIN="${ROOT}/solutions"
CLASS_DIR="${MAIN}/bin"
SRC_DIR="${MAIN}/src"
SCRIP_DIR="${MAIN}/sh"

# package
PACK="com/ciaoshen/howtomcatworks/ex15"
DIGESTER="${SRC_DIR}/${PACK}/digestertest"
BOOT="${SRC_DIR}/${PACK}/startup"
WEB="${SRC_DIR}/${PACK}/webroot"

# class prefix
PRE="com.ciaoshen.howtomcatworks.ex15"
PRE_BOOT="${PRE}.startup"
PRE_WEB="${PRE}.webroot"
PRE_DIGESTER="${PRE}.digestertest"

# lib
LIB="${ROOT}/lib"
SERVLET="${LIB}/servlet.jar"
COMMON="${LIB}/commons-collections.jar"
COMMON_DIGESTER="${LIB}/commons-digester.jar"
COMMON_LOG="${LIB}/commons-logging.jar"
TOMCAT_UTIL="${LIB}/tomcat-util.jar"
NAMING_COMMON="${LIB}/naming-common.jar"
NAMING_FACTORY="${LIB}/naming-factory.jar"
COMMON_BEAN="${LIB}/commons-beanutils.jar"



### 编译共享Servlet程序
javac -source 1.4 -d ${WEB_APPS} -cp "${CLASS_DIR}:${SERVLET}" "${WEB}/PrimitiveServlet.java" "${WEB}/ModernServlet.java"

############################################################ 
### 14章需要重新编译这些库，15章不需要
### >>> 编译新的org.apache.catalina.connector.http10.HttpProcessor.java <<<
### 为了显示HTTP请求的请求行和请求头
############################################################ 
CATA_SRC="${ROOT}/src/"
CATA_CLASS="${ROOT}"

### 重新编译HttpConnector.java
#javac -source 1.4 -d ${CATA_CLASS} -sourcepath ${CATA_SRC} -cp "${CATA_CLASS}:${LIB}/*" "${CATA_SRC}/org/apache/catalina/connector/http/HttpConnector.java"

### 重新编译HttpProcessor.java
#javac -source 1.4 -d ${CATA_CLASS} -sourcepath ${CATA_SRC} -cp "${CATA_CLASS}:${LIB}/*" "${CATA_SRC}/org/apache/catalina/connector/http/HttpProcessor.java"

### 重新编译StandardEngineMapper.java
#javac -source 1.4 -d ${CATA_CLASS} -sourcepath ${CATA_SRC} -cp "${CATA_CLASS}:${LIB}/*" "${CATA_SRC}/org/apache/catalina/core/StandardEngineMapper.java"



### 编译Test01.java
#javac -source 1.4 -d ${CLASS_DIR} -sourcepath ${SRC_DIR} -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON_DIGESTER}:${COMMON}:${COMMON_DIGESTER}:${COMMON_BEAN}:${COMMON_LOG}" "${DIGESTER}/Employee.java" "${DIGESTER}/Test01.java"

### 运行Test01.class
#java -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON_DIGESTER}:${COMMON}:${COMMON_DIGESTER}:${COMMON_BEAN}:${COMMON_LOG}" "${PRE_DIGESTER}.Test01"

### 编译Test02.java
#javac -source 1.4 -d ${CLASS_DIR} -sourcepath ${SRC_DIR} -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON_DIGESTER}:${COMMON}:${COMMON_DIGESTER}:${COMMON_BEAN}:${COMMON_LOG}" "${DIGESTER}/Office.java" "${DIGESTER}/Address.java" "${DIGESTER}/Employee.java" "${DIGESTER}/Test02.java"

### 运行Test02.class
#java -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON_DIGESTER}:${COMMON}:${COMMON_DIGESTER}:${COMMON_BEAN}:${COMMON_LOG}" "${PRE_DIGESTER}.Test02"

### 编译Test03.java
javac -source 1.4 -d ${CLASS_DIR} -sourcepath ${SRC_DIR} -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON_DIGESTER}:${COMMON}:${COMMON_DIGESTER}:${COMMON_BEAN}:${COMMON_LOG}" "${DIGESTER}/Office.java" "${DIGESTER}/Address.java" "${DIGESTER}/Employee.java" "${DIGESTER}/EmployeeRuleSet.java" "${DIGESTER}/Test03.java"

### 运行Test03.class
java -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON_DIGESTER}:${COMMON}:${COMMON_DIGESTER}:${COMMON_BEAN}:${COMMON_LOG}" "${PRE_DIGESTER}.Test03"

