#!/bin/bash
#############################################################
###
### How Tomcat Works - Chapter 10 
### Use this Script to run each exercise in Chapter 10
### Uncomment the specificate line to activate the command
###
#############################################################

# common dir
ROOT="/Users/Wei/github/HowTomcatWorks"
WEB_APPS="${ROOT}/webapps/app10/WEB-INF/classes/"
MAIN="${ROOT}/solutions"
CLASS_DIR="${MAIN}/bin"
SRC_DIR="${MAIN}/src"
SCRIP_DIR="${MAIN}/sh"

# package
PACK="com/ciaoshen/howtomcatworks/ex10"
BOOT="${SRC_DIR}/${PACK}/startup"
CORE="${SRC_DIR}/${PACK}/core"
WEB="${SRC_DIR}/${PACK}/webroot"
REALM="${SRC_DIR}/${PACK}/realm"

# class prefix
PRE="com.ciaoshen.howtomcatworks.ex10"
PRE_BOOT="${PRE}.startup"
PRE_CORE="${PRE}.core"
PRE_WEB="${PRE}.webroot"

# lib
LIB="${ROOT}/lib"
SERVLET="${LIB}/servlet.jar"
COMMON="${LIB}/commons-collections.jar"
COMMON_DIGESTER="${LIB}/commons-digester.jar"
COMMON_LOG="${LIB}/commons-logging.jar"



### 编译共享Servlet程序
javac -source 1.4 -d ${WEB_APPS} -sourcepath ${SRC_DIR} -cp "${CLASS_DIR}:${SERVLET}" "${WEB}/PrimitiveServlet.java" "${WEB}/ModernServlet.java"

##############################################################
# 编译运行TOMCAT-HOME/solutions/src/com/ciaoshen/howtomcatworks/ex10/Bootstrap1.java
##############################################################
### 编译Bootstrap1.java
#javac -source 1.4 -d ${CLASS_DIR} -sourcepath ${SRC_DIR} -cp "${CLASS_DIR}:${ROOT}:${SERVLET}" "${CORE}/SimpleContextConfig.java" "${CORE}/SimplePipeline.java" "${CORE}/SimpleWrapper.java" "${CORE}/SimpleWrapperValve.java" "${REALM}/SimpleRealm.java" "${BOOT}/Bootstrap1.java"

### 运行Bootstrap1.class
#java -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON}" "${PRE_BOOT}.Bootstrap1"

##############################################################
# 编译运行TOMCAT-HOME/solutions/src/com/ciaoshen/howtomcatworks/ex10/Bootstrap2.java
##############################################################
### 编译新的StandardWrapper
### 第10章不需要重写StandardWrapper。这是因为11章StandardWrapper#loadServlet()函数出bug，为了对照比较。
#CATA_SRC="${ROOT}/src/"
#CATA_CLASS="${ROOT}"

#javac -source 1.4 -d ${CATA_CLASS} -sourcepath ${CATA_SRC} -cp "${CATA_CLASS}:${LIB}/*" "${CATA_SRC}/org/apache/catalina/core/StandardWrapper.java"

### 编译Bootstrap2.java
javac -source 1.4 -d ${CLASS_DIR} -sourcepath ${SRC_DIR} -cp "${CLASS_DIR}:${ROOT}:${SERVLET}" "${CORE}/SimpleContextConfig.java" "${CORE}/SimplePipeline.java" "${CORE}/SimpleWrapper.java" "${CORE}/SimpleWrapperValve.java" "${REALM}/SimpleUserDatabaseRealm.java" "${BOOT}/Bootstrap2.java"

### 运行Bootstrap2.class
java -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON}:${COMMON_DIGESTER}:${COMMON_LOG}" "${PRE_BOOT}.Bootstrap2"


