#!/bin/bash
#############################################################
###
### How Tomcat Works - Chapter 6
### Use this Script to run each exercise in Chapter 6
### Uncomment the specificate line to activate the command
###
#############################################################

# common dir
ROOT="/Users/Wei/github/HowTomcatWorks"
MAIN="${ROOT}/solutions"
CLASS_DIR="${MAIN}/bin"
SRC_DIR="${MAIN}/src"
SCRIP_DIR="${MAIN}/sh"

# package
PACK="com/ciaoshen/howtomcatworks/ex06"
BOOT="${SRC_DIR}/${PACK}/startup"
CORE="${SRC_DIR}/${PACK}/core"
WEB="${SRC_DIR}/${PACK}/webroot"

# class prefix
PRE="com.ciaoshen.howtomcatworks.ex06"
PRE_BOOT="${PRE}.startup"
PRE_CORE="${PRE}.core"
PRE_WEB="${PRE}.webroot"

# lib
SERVLET="${ROOT}/lib/servlet.jar"


##############################################################
# Run TOMCAT-HOME/solutions/src/com/ciaoshen/howtomcatworks/ex06/Bootstrap.java
##############################################################
javac -d ${CLASS_DIR} -sourcepath ${SRC_DIR} -cp "${CLASS_DIR}:${ROOT}:${SERVLET}" "${CORE}/SimpleContext.java" "${CORE}/SimpleContextMapper.java" "${CORE}/SimpleContextValve.java" "${CORE}/SimpleLoader.java" "${CORE}/SimplePipeline.java" "${CORE}/SimpleWrapper.java" "${CORE}/SimpleWrapperValve.java" "${CORE}/SimpleContextLifecycleListener.java" "${WEB}/PrimitiveServlet.java" "${WEB}/ModernServlet.java" "${BOOT}/Bootstrap.java"

java -cp "${CLASS_DIR}:${ROOT}:${SERVLET}" "${PRE_BOOT}.Bootstrap"
