#!/bin/bash
#############################################################
###
### How Tomcat Works - Chapter 11 
### Use this Script to run each exercise in Chapter 11
### Uncomment the specificate line to activate the command
###
#############################################################

# common dir
ROOT="/Users/Wei/github/HowTomcatWorks"
WEB_APPS="${ROOT}/webapps/app11/WEB-INF/classes/"
MAIN="${ROOT}/solutions"
CLASS_DIR="${MAIN}/bin"
SRC_DIR="${MAIN}/src"
SCRIP_DIR="${MAIN}/sh"

# package
PACK="com/ciaoshen/howtomcatworks/ex11"
BOOT="${SRC_DIR}/${PACK}/startup"
CORE="${SRC_DIR}/${PACK}/core"
WEB="${SRC_DIR}/${PACK}/webroot"
REALM="${SRC_DIR}/${PACK}/realm"

# class prefix
PRE="com.ciaoshen.howtomcatworks.ex11"
PRE_BOOT="${PRE}.startup"
PRE_CORE="${PRE}.core"
PRE_WEB="${PRE}.webroot"

# lib
LIB="${ROOT}/lib"
SERVLET="${LIB}/servlet.jar"
COMMON="${LIB}/commons-collections.jar"
COMMON_DIGESTER="${LIB}/commons-digester.jar"
COMMON_LOG="${LIB}/commons-logging.jar"



### 编译共享Servlet程序
javac -source 1.4 -d ${WEB_APPS} -cp "${CLASS_DIR}:${SERVLET}" "${WEB}/PrimitiveServlet.java" "${WEB}/ModernServlet.java"

##############################################################
# 编译运行TOMCAT-HOME/solutions/src/com/ciaoshen/howtomcatworks/ex11/Bootstrap.java
##############################################################
### 重新编译org.apache.catalina
CATA_SRC="${ROOT}/src/"
CATA_CLASS="${ROOT}"


############################################################ 
### >>> 编译新的StandardWrapper <<<
### 因为loadServlet()函数里关于SystemLogHandler的代码有bug
### 具体原因现在还不清楚
### 但注释掉那两行之后可以正常运行
############################################################ 
javac -source 1.4 -d ${CATA_CLASS} -sourcepath ${CATA_SRC} -cp "${CATA_CLASS}:${LIB}/*" "${CATA_SRC}/org/apache/catalina/core/StandardWrapper.java"

### 编译Bootstrap.java
javac -source 1.4 -d ${CLASS_DIR} -sourcepath ${SRC_DIR} -cp "${CLASS_DIR}:${ROOT}:${SERVLET}" "${CORE}/SimpleContextConfig.java" "${BOOT}/Bootstrap.java"

### 运行Bootstrap.class
java -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON}" "${PRE_BOOT}.Bootstrap"
