#!/bin/bash
#############################################################
###
### How Tomcat Works - Chapter 12 
### Use this Script to run each exercise in Chapter 12
### Uncomment the specificate line to activate the command
### 12章没有练习
### 这里的代码是为了测试StandardContext类中几个重要属性
###
#############################################################

# common dir
ROOT="/Users/Wei/github/HowTomcatWorks"
WEB_APPS="${ROOT}/webapps/app12/WEB-INF/classes/"
MAIN="${ROOT}/solutions"
CLASS_DIR="${MAIN}/bin"
SRC_DIR="${MAIN}/src"
SCRIP_DIR="${MAIN}/sh"

# package
PACK="com/ciaoshen/howtomcatworks/ex12"
BOOT="${SRC_DIR}/${PACK}/startup"
CORE="${SRC_DIR}/${PACK}/core"
WEB="${SRC_DIR}/${PACK}/webroot"
REALM="${SRC_DIR}/${PACK}/realm"

# class prefix
PRE="com.ciaoshen.howtomcatworks.ex12"
PRE_BOOT="${PRE}.startup"
PRE_CORE="${PRE}.core"
PRE_WEB="${PRE}.webroot"

# lib
LIB="${ROOT}/lib"
SERVLET="${LIB}/servlet.jar"
COMMON="${LIB}/commons-collections.jar"
COMMON_DIGESTER="${LIB}/commons-digester.jar"
COMMON_LOG="${LIB}/commons-logging.jar"
TOMCAT_UTIL="${LIB}/tomcat-util.jar"



### 编译共享Servlet程序
javac -source 1.4 -d ${WEB_APPS} -cp "${CLASS_DIR}:${SERVLET}" "${WEB}/PrimitiveServlet.java" "${WEB}/ModernServlet.java"

############################################################ 
### >>> 编译新的org.apache.catalina.StandardContext <<<
### 为了看清StandardContext中几个重要属性的实际值
############################################################ 
CATA_SRC="${ROOT}/src/"
CATA_CLASS="${ROOT}"

javac -source 1.4 -d ${CATA_CLASS} -sourcepath ${CATA_SRC} -cp "${CATA_CLASS}:${TOMCAT_UTIL}:${LIB}/*" "${CATA_SRC}/org/apache/catalina/core/StandardContext.java"

############################################################ 
### >>> 编译新的org.apache.catalina.StandardContextMapper <<<
### 为了看清楚“4步走”陪陪规则：
###	1. Exaxt Match
###	2. Prifix Match
###	3. Extension Match
### 	4. Default Match
############################################################ 
javac -source 1.4 -d ${CATA_CLASS} -sourcepath ${CATA_SRC} -cp "${CATA_CLASS}:${TOMCAT_UTIL}:${LIB}/*" "${CATA_SRC}/org/apache/catalina/core/StandardContextMapper.java"

### 编译Bootstrap.java
javac -source 1.4 -d ${CLASS_DIR} -sourcepath ${SRC_DIR} -cp "${CLASS_DIR}:${ROOT}:${SERVLET}" "${CORE}/SimpleContextConfig.java" "${BOOT}/Bootstrap.java"

### 运行Bootstrap.class
java -cp "${CLASS_DIR}:${ROOT}:${SERVLET}:${COMMON}" "${PRE_BOOT}.Bootstrap"
